version: '3.1'

services:

  database:
    image: mongo
    container_name: yolo-mongo-db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - yoloapp-network
    volumes:
      - type: volume
        source: yolo-data-volume
        target: /data/db

  backend:
    image: pharesd/yolo-backend:v0.0.1
    container_name: yolo-backend
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    restart: always
    depends_on: 
      - database
    ports:
      - "5000:5000"
    networks:
      - yoloapp-network

  client:
    image: pharesd/yolo-client:v0.0.1
    container_name: yolo-client
    build:
      context: ./client
      dockerfile: Dockerfile-client
    stdin_open: true
    tty: true
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - yoloapp-network

networks:
  yoloapp-network:
    name: yolo-app-network
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.17.0.0/16
          ip_range: 172.17.0.0/16

volumes:
  yolo-data-volume:
    driver: local