version: '3.1'

services:

  mongo_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: contextPath
      dockerfile: backend/Dockerfile-backend
    depends_on: 
      - mongo_db
    ports:
      - 5000:5000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - yolo-network

  client:
    build:
      context: app/client
      dockerfile: client/Dockerfile-client
    ports:
      - 3000=3000
    networks:
      - yolo-network

networks:
  yolo-network:
    driver: bridge