- hosts: all
  become: true
  gather_facts: false
  roles:
    - install_docker
    - git_clone
    - create_docker_network
    - create_docker_volume
    - database_container
    - backend_container
    - client_container
