---
- name: Deploy backend container
  community.docker.docker_container:
    name: yolo-backend
    image: pharesd/yolo-backend:v0.0.1
    command: tail -f /dev/null
    state: started
    ports:
    - 5000:5000
    networks:
    - name: yolo-network