- name: Create yolo network
  community.docker.docker_network:
    name: yolo-network
    state: present
    #driver_options:
    #  com.docker.network.bridge.name: net2
    #ipam_config:
    #- subnet: 172.23.27.0/24
    #  gateway: 172.23.27.2
    #  iprange: 172.23.27.0/26
- name: Create a volume
  community.docker.docker_volume:
    name: yolo-vol
    #driver_options:
    #  type: btrfs
    #  device: /dev/sda2

- name: Deploy mongodb
  community.docker.docker_container:
    name: mongo-db
    image: mongo
    restart_policy: always
    ports:
    - "27017:27017"
    #volumes:
    #- name: yolo-vol
    #- type: volume
    #  source: /dev/sda2
    #  target: /data/db
    networks:
    - name: yolo-network