
- name: Deploy mongodb
  community.docker.docker_container:
    name: yolo-mongo-db
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - yolo-vol: /data/db
    networks:
    - name: yolo-network
    state: started