apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-mongo-db
  labels:
    app: yolo-mongo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-mongo-db
  template:
    metadata:
      labels:
        app: yolo-mongo-db
    spec:
      containers:
      - name: yolo-mongo-db
        image: mongo
        ports:
        - containerPort: 27017

